id = "Twilight"
name = "Twilight Theme"
description = "A variation of a classic Textmate theme."
version = "0.1.0"
schema_version = 1
authors = ["<git@getpanda.me>"]
repository = "https://github.com/tectiv3/twilight-zed"